docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - v1:
      - Introduction: v1/intro.md
      - "Select Adapter": v1/db-select.md
      - "TableGateway Adapter": v1/db-table-gateway.md
site_name: 'phpdb-paginator-adapter'
site_description: 'phpdb adapters for laminas-paginator'
repo_url: 'https://github.com/php-db/phpdb-paginator-adapter'
extra:
    project: Components
    installation:
        config_provider_class: 'PhpDb\Paginator\Adapter\ConfigProvider'
        module_class: 'PhpDb\Paginator\Adapter\Module'
    current_version: v1
    versions:
      - v1
